###登录 login
POST {{host}}/api/system/user/login
Content-Type: application/json

{
  "account": "18613030352",
  "password": "123456"
}
> {% client.global.set("token", response.body.data.token); %}



###查询登录日志 queryLoginLogList
POST {{host}}/api/log/login/queryLoginLogList
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "pageNo": 1,
  "pageSize": 10
}

###查询登录日志统计信息 statisticsLoginLog
GET {{host}}/api/log/login/statisticsLoginLog
Authorization: Bearer {{token}}

###查询登录日志 queryLoginLogList
POST {{host}}/api/log/operate/queryOperateLogList
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "pageNo": 1,
  "pageSize": 10
}