// Code generated by hertz generator.

package role

import (
	"context"
	"hertz_admin/biz/dal/entity"
	"time"

	"github.com/cloudwego/hertz/pkg/app"
	role "hertz_admin/biz/model/role"
)

// RoleList .
// @router /role_list [POST]
func RoleList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req role.RoleListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	roles, total, err := entity.QuerySysRole(&req.RoleName, req.PageNo, req.PageSize)

	var list []*role.RoleListData

	for _, item := range roles {
		list = append(list, &role.RoleListData{
			Id:         item.Id,
			CreateTime: item.GmtCreate.Format("2006-01-02 15:04:05"),
			UpdateTime: item.GmtModified.Format("2006-01-02 15:04:05"),
			StatusId:   item.StatusId,
			Sort:       item.Sort,
			RoleName:   item.RoleName,
			Remark:     item.Remark,
		})
	}

	c.JSON(200, role.RoleListResp{
		Msg:      "successful",
		Code:     0,
		PageNo:   req.PageNo,
		PageSize: req.PageSize,
		Total:    total,
		Data:     list,
	})
}

// RoleSave .
// @router /role_save [POST]
func RoleSave(ctx context.Context, c *app.RequestContext) {
	var err error
	var req role.RoleSaveReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	err = entity.CreateSysRole([]entity.SysRole{{
		GmtCreate:   time.Now(),
		GmtModified: time.Time{},
		StatusId:    0,
		Sort:        0,
		RoleName:    "",
		Remark:      "",
	},
	})

	if err != nil {

	}

	resp := new(role.RoleSaveResp)

	c.JSON(200, resp)
}

// RoleUpdate .
// @router /role_update [POST]
func RoleUpdate(ctx context.Context, c *app.RequestContext) {
	var err error
	var req role.RoleUpdateReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	err = entity.UpdateSysRole(entity.SysRole{
		Id:          req.Id,
		GmtCreate:   time.Now(),
		GmtModified: time.Time{},
		StatusId:    0,
		Sort:        0,
		RoleName:    "",
		Remark:      "",
	})

	if err != nil {

	}
	resp := new(role.RoleUpdateResp)

	c.JSON(200, resp)
}

// RoleDelete .
// @router /role_delete [POST]
func RoleDelete(ctx context.Context, c *app.RequestContext) {
	var err error
	var req role.RoleDeleteReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	err = entity.DeleteSysUser(req.Ids)
	if err != nil {
		return
	}
	resp := new(role.RoleDeleteResp)

	c.JSON(200, resp)
}

// QueryRoleMenu .
// @router /query_role_menu [POST]
func QueryRoleMenu(ctx context.Context, c *app.RequestContext) {
	var err error
	var req role.QueryRoleMenuReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	resp := new(role.QueryRoleMenuResp)

	c.JSON(200, resp)
}

// UpdateRoleMenu .
// @router /update_role_menu [POST]
func UpdateRoleMenu(ctx context.Context, c *app.RequestContext) {
	var err error
	var req role.UpdateRoleMenuReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	resp := new(role.UpdateRoleMenuResp)

	c.JSON(200, resp)
}
