// Code generated by hertz generator.

package dicttype

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/feihua/hertz-admin/biz/pkg/mw"
)

func rootMw() []app.HandlerFunc {
	var hf []app.HandlerFunc
	hf = append(hf, mw.JwtMiddleware.MiddlewareFunc())
	return hf
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _systemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dicttypeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adddicttypeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletedicttypeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querydicttypedetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querydicttypelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatedicttypeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatedicttypestatusMw() []app.HandlerFunc {
	// your code...
	return nil
}
