// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/feihua/hertz-admin/biz/handler/other"
	"github.com/feihua/hertz-admin/biz/pkg/mw"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.POST("/api/system/user/login", mw.JwtMiddleware.LoginHandler)
	r.GET("/ping", other.Ping)

	// your code ...
}
