// Code generated by hertz generator.

package menu

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/feihua/hertz-admin/biz/pkg/mw"
)

func rootMw() []app.HandlerFunc {
	var hf []app.HandlerFunc
	hf = append(hf, mw.JwtMiddleware.MiddlewareFunc())
	return hf
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _systemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _menuMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addmenuMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletemenuMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querymenudetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querymenulistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatemenuMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatemenustatusMw() []app.HandlerFunc {
	// your code...
	return nil
}
