// Code generated by hertz generator.

package role

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryrolemenuMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _roledeleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _rolelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _rolesaveMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _roleupdateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updaterolemenuMw() []app.HandlerFunc {
	// your code...
	return nil
}
