// Code generated by hertz generator.

package dept

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/feihua/hertz-admin/biz/pkg/mw"
)

func rootMw() []app.HandlerFunc {
	var hf []app.HandlerFunc
	hf = append(hf, mw.JwtMiddleware.MiddlewareFunc())
	return hf
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _systemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deptMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adddeptMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletedeptMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querydeptdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querydeptlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatedeptMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatedeptstatusMw() []app.HandlerFunc {
	// your code...
	return nil
}
