// Code generated by hertz generator.

package operatelog

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/feihua/hertz-admin/biz/pkg/mw"
)

func rootMw() []app.HandlerFunc {
	var hf []app.HandlerFunc
	hf = append(hf, mw.JwtMiddleware.MiddlewareFunc())
	return hf
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _systemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _operatelogMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteoperatelogMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryoperatelogdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryoperateloglistMw() []app.HandlerFunc {
	// your code...
	return nil
}
