// Code generated by hertz generator.

package loginlog

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	loginlog "github.com/feihua/hertz-admin/biz/model/system/loginlog"
)

// DeleteLoginLog .
// @router /api/system/loginLog/deleteLoginLog [POST]
func DeleteLoginLog(ctx context.Context, c *app.RequestContext) {
	var err error
	var req loginlog.DeleteLoginLogReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(loginlog.DeleteLoginLogResp)

	c.JSON(consts.StatusOK, resp)
}

// QueryLoginLogDetail .
// @router /api/system/loginLog/queryLoginLogDetail [POST]
func QueryLoginLogDetail(ctx context.Context, c *app.RequestContext) {
	var err error
	var req loginlog.QueryLoginLogDetailReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(loginlog.QueryLoginLogDetailResp)

	c.JSON(consts.StatusOK, resp)
}

// QueryLoginLogList .
// @router /api/system/loginLog/queryLoginLogList [POST]
func QueryLoginLogList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req loginlog.QueryLoginLogListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(loginlog.QueryLoginLogListResp)

	c.JSON(consts.StatusOK, resp)
}
