// Code generated by hertz generator.

package loginlog

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/feihua/hertz-admin/biz/pkg/mw"
)

func rootMw() []app.HandlerFunc {
	var hf []app.HandlerFunc
	hf = append(hf, mw.JwtMiddleware.MiddlewareFunc())
	return hf
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _systemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginlogMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteloginlogMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryloginlogdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryloginloglistMw() []app.HandlerFunc {
	// your code...
	return nil
}
