// Code generated by hertz generator.

package menu

import (
	"github.com/cloudwego/hertz/pkg/app"
	"hertz_admin/biz/pkg/mw"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _menuMw() []app.HandlerFunc {
	var hf []app.HandlerFunc
	hf = append(hf, mw.JwtMiddleware.MiddlewareFunc())
	return hf
}

func _menudeleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _menulistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _menusaveMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _menuupdateMw() []app.HandlerFunc {
	// your code...
	return nil
}
