// Code generated by hertz generator.

package handler

import (
	"context"
	"encoding/json"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/feihua/hertz-admin/biz/pkg/http"
)

type LoginReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

// Ping .
func Ping(ctx context.Context, c *app.RequestContext) {

	data := LoginReq{
		"18800000000",
		"123456",
	}

	bytes, _ := json.Marshal(data)
	res, _ := http.Post("http://175.178.110.17:8088/api/login", bytes)

	welcome, err := UnmarshalWelcome(res)
	if err != nil {
		return
	}

	c.JSON(200, welcome)
}

func UnmarshalWelcome(data []byte) (Welcome, error) {
	var r Welcome
	err := json.Unmarshal(data, &r)
	return r, err
}

func (r *Welcome) Marshal() ([]byte, error) {
	return json.Marshal(r)
}

type Welcome struct {
	Msg    string `json:"msg"`
	Code   int64  `json:"code"`
	Status string `json:"status"`
	Data   Data   `json:"data"`
}

type Data struct {
	Mobile string `json:"mobile"`
	Token  string `json:"token"`
}
