// Code generated by hertz generator.

package post

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/feihua/hertz-admin/biz/pkg/mw"
)

func rootMw() []app.HandlerFunc {
	var hf []app.HandlerFunc
	hf = append(hf, mw.JwtMiddleware.MiddlewareFunc())
	return hf
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _systemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _postMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addpostMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletepostMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querypostdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querypostlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatepostMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatepoststatusMw() []app.HandlerFunc {
	// your code...
	return nil
}
