// Code generated by hertz generator.

package menu

import (
	"context"
	"hertz_admin/biz/dal/entity"
	"time"

	"github.com/cloudwego/hertz/pkg/app"
	menu "hertz_admin/biz/model/menu"
)

// MenuList .
// @router /menu_list [POST]
func MenuList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req menu.MenuListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	menus, total, err := entity.QuerySysMenu(&req.MenuName, 1, 1000)

	var list []*menu.MenuListData

	for _, item := range menus {
		list = append(list, &menu.MenuListData{
			Id:         item.Id,
			CreateTime: item.GmtCreate.Format("2006-01-02 15:04:05"),
			UpdateTime: item.GmtModified.Format("2006-01-02 15:04:05"),
			StatusId:   item.StatusId,
			Sort:       item.Sort,
			ParentId:   item.ParentId,
			MenuName:   item.MenuName,
			MenuUrl:    item.MenuUrl,
			ApiUrl:     item.ApiUrl,
			MenuIcon:   item.MenuIcon,
			Remark:     item.Remark,
			MenuType:   item.MenuType,
		})
	}

	c.JSON(200, menu.MenuListResp{
		Msg:   "successful",
		Code:  0,
		Total: total,
		Data:  list,
	})
}

// MenuSave .
// @router /menu_save [POST]
func MenuSave(ctx context.Context, c *app.RequestContext) {
	var err error
	var req menu.MenuSaveReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	err = entity.CreateSysMenu([]entity.SysMenu{{
		GmtCreate:   time.Now(),
		GmtModified: time.Time{},
		StatusId:    0,
		Sort:        0,
		ParentId:    0,
		MenuName:    "",
		MenuUrl:     "",
		ApiUrl:      "",
		MenuIcon:    "",
		Remark:      req.Remark,
		MenuType:    0,
	}})

	if err != nil {

	}
	resp := new(menu.MenuSaveResp)

	c.JSON(200, resp)
}

// MenuUpdate .
// @router /menu_update [POST]
func MenuUpdate(ctx context.Context, c *app.RequestContext) {
	var err error
	var req menu.MenuUpdateReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	err = entity.UpdateSysMenu(entity.SysMenu{
		Id:          req.Id,
		GmtCreate:   time.Now(),
		GmtModified: time.Time{},
		StatusId:    0,
		Sort:        0,
		ParentId:    0,
		MenuName:    "",
		MenuUrl:     "",
		ApiUrl:      "",
		MenuIcon:    "",
		Remark:      req.Remark,
		MenuType:    0,
	})

	if err != nil {

	}

	resp := new(menu.MenuUpdateResp)

	c.JSON(200, resp)
}

// MenuDelete .
// @router /menu_delete [POST]
func MenuDelete(ctx context.Context, c *app.RequestContext) {
	var err error
	var req menu.MenuDeleteReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	err = entity.DeleteSysMenu(req.Ids)
	if err != nil {
		return
	}

	resp := new(menu.MenuDeleteResp)

	c.JSON(200, resp)
}
