// Code generated by hertz generator. DO NOT EDIT.

package system

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	dept "github.com/feihua/hertz-admin/biz/router/system/dept"
	dictdata "github.com/feihua/hertz-admin/biz/router/system/dictdata"
	dicttype "github.com/feihua/hertz-admin/biz/router/system/dicttype"
	loginlog "github.com/feihua/hertz-admin/biz/router/system/loginlog"
	menu "github.com/feihua/hertz-admin/biz/router/system/menu"
	notice "github.com/feihua/hertz-admin/biz/router/system/notice"
	operatelog "github.com/feihua/hertz-admin/biz/router/system/operatelog"
	post "github.com/feihua/hertz-admin/biz/router/system/post"
	role "github.com/feihua/hertz-admin/biz/router/system/role"
	user "github.com/feihua/hertz-admin/biz/router/system/user"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	user.Register(r)

	role.Register(r)

	post.Register(r)

	operatelog.Register(r)

	notice.Register(r)

	menu.Register(r)

	loginlog.Register(r)

	dicttype.Register(r)

	dictdata.Register(r)

	dept.Register(r)
}
