apiVersion: apps/v1
kind: Deployment
metadata:
  name: hertz-admin
  namespace: zero-admin
  labels:
    app: hertz-admin
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: hertz-admin
  template:
    metadata:
      labels:
        app: hertz-admin
    spec:
      containers:
        - name: hertz-admin
          image: hertz-admin:0.0.1
          ports:
            - containerPort: 6666

---
apiVersion: v1
kind: Service
metadata:
  name: hertz-admin-svc
  namespace: zero-admin
  labels:
    app: hertz-admin-svc
spec:
  ports:
    - port: 6666
      name: hertz-admin
      targetPort: 6666
  selector:
    app: hertz-admin
  type: NodePort
