// Code generated by hertz generator.

package user

import (
	"context"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"hertz_admin/biz/dal/entity"
	"time"

	"github.com/cloudwego/hertz/pkg/app"
	user "hertz_admin/biz/model/user"
)

// QueryUserMenu .
// @router /query_user_menu [POST]
func QueryUserMenu(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.QueryUserMenuReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	resp := new(user.QueryUserMenuResp)

	c.JSON(200, resp)
}

// UserList .
// @router /user_list [POST]
func UserList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UserListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	users, total, err := entity.QuerySysUser(nil, req.PageNo, req.PageSize)

	hlog.Infof("Hello, hertz %d", total)

	var list []*user.UserListData

	for _, item := range users {
		list = append(list, &user.UserListData{
			Id:         item.Id,
			StatusId:   item.StatusId,
			Sort:       item.Sort,
			UserNo:     item.UserNo,
			Mobile:     item.Mobile,
			RealName:   item.RealName,
			Remark:     item.Remark,
			CreateTime: item.GmtCreate.Format("2006-01-02 15:04:05"),
			UpdateTime: item.GmtModified.Format("2006-01-02 15:04:05"),
		})
	}

	c.JSON(200, user.UserListResp{
		Msg:      "successful",
		Code:     0,
		PageNo:   req.PageNo,
		PageSize: req.PageSize,
		Total:    total,
		Data:     list,
	})
}

// UserSave .
// @router /user_save [POST]
func UserSave(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UserSaveReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	err = entity.CreateSysUser([]entity.SysUser{
		{
			GmtCreate: time.Now(),
			StatusId:  0,
			Sort:      0,
			UserNo:    0,
			Mobile:    req.Mobile,
			RealName:  req.RealName,
			Remark:    req.Remark,
			Password:  "123456",
		},
	})

	if err != nil {

	}
	resp := new(user.UserSaveResp)

	c.JSON(200, resp)
}

// UserUpdate .
// @router /user_update [POST]
func UserUpdate(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UserUpdateReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	err = entity.UpdateSysUser(entity.SysUser{
		Id:        req.Id,
		GmtCreate: time.Now(),
		StatusId:  0,
		Sort:      0,
		UserNo:    0,
		Mobile:    req.Mobile,
		RealName:  req.RealName,
		Remark:    req.Remark,
	})

	if err != nil {

	}
	resp := new(user.UserUpdateResp)

	c.JSON(200, resp)
}

// UserDelete .
// @router /user_delete [POST]
func UserDelete(ctx context.Context, c *app.RequestContext) {
	//var err error
	//var req user.UserDeleteReq
	//err = c.BindAndValidate(&req)
	//if err != nil {
	//	c.JSON(200, {
	//		Msg:  err.Error(),
	//		Code: 1,
	//	})
	//	return
	//}

	//err = entity.DeleteSysUser(req.Ids)
	//if err != nil {
	//	c.JSON(200, user.ErrorResp{
	//		Msg:  err.Error(),
	//		Code: 1,
	//	})
	//	return
	//}

	resp := new(user.UserDeleteResp)

	c.JSON(200, resp)
}
