// Code generated by hertz generator.

package role

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/feihua/hertz-admin/biz/pkg/mw"
)

func rootMw() []app.HandlerFunc {
	var hf []app.HandlerFunc
	hf = append(hf, mw.JwtMiddleware.MiddlewareFunc())
	return hf
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _systemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _roleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addroleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _batchauthuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _batchcancelauthuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _cancelauthuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteroleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryallocatedlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryroledetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryrolelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryrolemenulistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryunallocatedlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateroleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addrolemenuMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updaterolestatusMw() []app.HandlerFunc {
	// your code...
	return nil
}
