// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysRoleMenu = "sys_role_menu"

// SysRoleMenu 菜单角色关联表
type SysRoleMenu struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                          // 主键
	RoleID     int64     `gorm:"column:role_id;not null;comment:角色ID" json:"role_id"`                                   // 角色ID
	MenuID     int64     `gorm:"column:menu_id;not null;comment:菜单ID" json:"menu_id"`                                   // 菜单ID
	StatusID   int32     `gorm:"column:status_id;not null;default:1;comment:状态(1:正常，0:禁用)" json:"status_id"`            // 状态(1:正常，0:禁用)
	Sort       int32     `gorm:"column:sort;not null;default:1;comment:排序" json:"sort"`                                 // 排序
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:修改时间" json:"update_time"` // 修改时间
}

// TableName SysRoleMenu's table name
func (*SysRoleMenu) TableName() string {
	return TableNameSysRoleMenu
}
