// Code generated by hertz generator.

package user

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/feihua/hertz-admin/biz/pkg/mw"
)

func rootMw() []app.HandlerFunc {
	var hf []app.HandlerFunc
	hf = append(hf, mw.JwtMiddleware.MiddlewareFunc())
	return hf
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _systemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adduserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryuserdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryuserlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryusermenuMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryuserrolelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adduserroleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateuserstatusMw() []app.HandlerFunc {
	// your code...
	return nil
}
