// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	menu "hertz_admin/biz/router/menu"
	role "hertz_admin/biz/router/role"
	user "hertz_admin/biz/router/user"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	menu.Register(r)

	role.Register(r)

	user.Register(r)
}
